version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sio_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sio_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sio-network

volumes:
  pgdata:

networks:
  sio-network:
    driver: bridge